config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root "daily_reports#index"
  
  get "timeline", to: "timeline#index"
  
  resources :daily_reports
  
  resources :users, only: [:index, :show] do
    member do
      get :followers
      get :following
    end
  end
  
  resources :follows, only: [:create, :destroy], param: :user_id
  
  resource :profile, only: [:edit, :update], controller: 'profile'

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= content_for(:title) || "Dairy Report"
    %meta{name: "viewport", content: "width=device-width,initial-scale=1"}
    %meta{name: "apple-mobile-web-app-capable", content: "yes"}
    %meta{name: "mobile-web-app-capable", content: "yes"}
    = csrf_meta_tags
    = csp_meta_tag

    = yield :head

    %link{rel: "icon", href: "/icon.png", type: "image/png"}
    %link{rel: "icon", href: "/icon.svg", type: "image/svg+xml"}
    %link{rel: "apple-touch-icon", href: "/icon.png"}

    %link{href: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css", rel: "stylesheet"}
    
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
    
    %link{rel: "stylesheet", href: "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"}

  %body
    %nav.navbar.navbar-expand-lg.navbar-dark.bg-primary.mb-4
      .container
        = link_to "Daily Report", root_path, class: "navbar-brand"
        
        %button.navbar-toggler{type: "button", "data-bs-toggle": "collapse", "data-bs-target": "#navbarNav"}
          %span.navbar-toggler-icon
        
        .collapse.navbar-collapse#navbarNav
          %ul.navbar-nav.me-auto
            - if user_signed_in?
              %li.nav-item
                = link_to "マイ日報", daily_reports_path, class: "nav-link"
              %li.nav-item
                = link_to "タイムライン", timeline_path, class: "nav-link"
              %li.nav-item
                = link_to "ユーザー一覧", users_path, class: "nav-link"
              %li.nav-item
                %a.nav-link{href: "#", "data-bs-toggle": "modal", "data-bs-target": "#newReportModal"}
                  新しい日報
          
          %ul.navbar-nav
            - if user_signed_in?
              %li.nav-item.dropdown
                %a.nav-link.dropdown-toggle{href: "#", id: "navbarDropdown", role: "button", "data-bs-toggle": "dropdown", "aria-expanded": "false"}
                  = current_user.display_name_or_username
                %ul.dropdown-menu
                  %li= link_to "プロフィール詳細", user_path(current_user), class: "dropdown-item"
                  %li= link_to "プロフィール編集", edit_profile_path, class: "dropdown-item"
                  %li= link_to "アカウント設定", edit_user_registration_path, class: "dropdown-item"
                  %li
                    %hr.dropdown-divider
                  %li= button_to "ログアウト", destroy_user_session_path, method: :delete, class: "dropdown-item"
            - else
              %li.nav-item
                = link_to "ログイン", new_user_session_path, class: "nav-link"
              %li.nav-item
                = link_to "新規登録", new_user_registration_path, class: "nav-link"

    .container
      - flash.each do |type, message|
        .alert{class: "alert-#{type == 'notice' ? 'success' : 'danger'} alert-dismissible fade show", role: "alert"}
          = message
          %button.btn-close{type: "button", "data-bs-dismiss": "alert"}

    .container
      = yield

    - if user_signed_in?
      = render "daily_reports/new_modal"

    %script{src: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"}